/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Blink LEDs based on switch input
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 * Write a program to control alternate LEDs to blink based on which switch is pressed/triggered. E.g.: Switch 1 pressed Green and Red LEDs starts blinking, switch 2 pressed, Blue and Yellow LED starts blinking and so on. Also delays in the blinking should be constant.
 * 
 * Algorithm:
 * 1. Initialize the GPIO pins
 * 2. Check which button is pressed
 * 3. Toggle LEDs based on which button is pressed
 * 4. Software Delay
 * 
 */

#include <stdint.h>
#include <stm32f405xx.h>

void init(void);
void check_button(void);
void toggle_led(void);
void delay(uint32_t);
uint8_t button_1 = 0; // State of LEDs related to button 1
uint8_t button_2 = 0; // State of LEDs related to button 2

int main(void)
{
    init();

    while (1)
    {
        check_button(); // Check which button is pressed
    }
}

/**
 * Initialize the GPIO pins
 * PC6 - Green LED
 * PB13 - Red LED
 * PB14 - Blue LED
 * PB15 - Yellow LED
 * PB3 - Button 1
 * PB7 - Button 2
 */
void init(void)
{
    /**
     *  Enable the clock to GPIO Port B and C
     */
    RCC->AHB1ENR |= (3 << 1);

    /**
     *  Set output for four LEDs (PC6, PB13, PB14 and PB15)
     */
    GPIOC->MODER &= ~(3 << 12); // Clear Mode of PC6
    GPIOC->MODER |= (1 << 12);  // Set output mode for PC6

    GPIOB->MODER &= ~(3 << 26);                        // Clear Mode of PB13
    GPIOB->MODER &= ~(3 << 28);                        // Clear Mode of PB14
    GPIOB->MODER &= ~(3 << 30);                        // Clear Mode of PB15
    GPIOB->MODER |= (1 << 26) | (1 << 28) | (1 << 30); // Set output mode for PB13, PB14 and PB15

    GPIOC->ODR |= (1 << 6);                          // Turn off Green LED
    GPIOB->ODR |= (1 << 13) | (1 << 14) | (1 << 15); // Turn off Red, Blue and Yellow LEDs

    /**
     * Set input for two buttons (PB3 and PB7)
     */
    GPIOB->MODER &= ~(3 << 6);  // Set input mode for PB3
    GPIOB->MODER &= ~(3 << 14); // Set input mode for PB7
}

/**
 * Check which button is pressed
 * PB3 - Button 1
 * PB7 - Button 2
 */
void check_button()
{
    if (!(GPIOB->IDR & (1 << 3))) // Check if button 1 is pressed
    {
        while (!(GPIOB->IDR & (1 << 3)))
            ;              // Wait for button to be released
        if (button_1 == 0) // If Red and Green LEDs are off, turn them on and turn off Blue and Yellow LEDs
        {
            button_1 = 1;
            button_2 = 0;

            GPIOB->ODR |= (1 << 14);
            GPIOB->ODR |= (1 << 15);
        }
        else // If Red and Green LEDs are on, turn them off
        {
            button_1 = 0;

            GPIOC->ODR |= (1 << 6);
            GPIOB->ODR |= (1 << 13);
        }
    }
    else if (!(GPIOB->IDR & (1 << 7)))
    {
        while (!(GPIOB->IDR & (1 << 7)))
            ; // Wait for button to be released
        if (button_2 == 0)
        {
            button_2 = 1;
            button_1 = 0;

            GPIOC->ODR |= (1 << 6);
            GPIOB->ODR |= (1 << 13);
        }
        else
        {
            button_2 = 0;

            GPIOB->ODR |= (1 << 14);
            GPIOB->ODR |= (1 << 15);
        }
    }

    toggle_led();
    delay(1000000);
}

/**
 * Toggle LEDs based on which button is pressed
 */
void toggle_led(void)
{
    if (button_1)
    {
        GPIOC->ODR ^= (1 << 6);
        GPIOB->ODR ^= (1 << 13);
    }
    else if (button_2)
    {
        GPIOB->ODR ^= (1 << 14);
        GPIOB->ODR ^= (1 << 15);
    }
}

/**
 * Software Delay
 */
void delay(uint32_t count)
{
    for (uint32_t i = 0; i < count; i++)
        ;
}
