/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Use DAC to control LED intensity
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <common.h>
#include <math.h>

// {2048, 3071, 3821, 3071, 2048, 1024, 274, 0, 274, 1024}

void init();
void loop();
int sineWave(uint32_t);

int main(void)
{
  lcd_init(BIT_4_MODE);
  lcd_print(0, 0, "Initializing");
  init();
  set_lcd_mode(CLEAR_SCREEN);
  lcd_print(0, 0, "Sin(    )");
  lcd_print(0, 1, "V:     DAC:");
  loop();
}

void init(void)
{
  RCC->AHB1ENR |= (1 << 0);  // Enable GPIOA clock
  GPIOA->MODER &= ~(3 << 8); // Clear PA4 mode bits
  GPIOA->MODER |= (3 << 8);  // Set PA4 to analog mode

  RCC->AHB1ENR |= (1 << 2);   // Enable GPIOC clock
  GPIOC->MODER &= ~(3 << 12); // Clear PC6 mode bits
  GPIOC->MODER |= (3 << 12);  // Set PC6 to analog mode

  RCC->APB1ENR |= (1 << 29); // Enable DAC clock
  DAC->CR |= (1 << 0);       // Enable DAC channel 1
}

int sineWave(uint32_t angle)
{
  double radians = angle * 3.14 / 180;
  double sine = (angle == 0 ? 0 : sin(radians));
  int result = (2.5 + 2.5 * sine);
  return result;
}

void loop()
{
  int sine;
  while (1)
  {
    for (uint32_t i = 0; i < 360; i++)
    {
      sine = sineWave(i);
      lcd_print_int(4, 0, i, 1);
      lcd_print_int(2, 1, sine, 1);
      lcd_print_int(12, 1, sine * 819, 1);
      DAC->DHR12R1 = sine * 819;
      delay(10);
    }
  }
}
