/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Clock
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <lcd.h>

void timer_delay(uint32_t);
void seconds_increment();
void minutes_increment();
void hours_increment();
void init();

char seconds[3] = "00";
char minutes[3] = "14";
char hours[3] = "02";
uint8_t AM = 0;

int main(void)
{
    init();

    while (1)
    {
        timer_delay(1);
        seconds_increment();
    }
}

void init()
{
    lcd_init(BIT_4_MODE);
    lcd_print(0, 0, "Clock Init");
    lcd_print(0, 1, "Please Wait!");

    RCC->APB1ENR |= (1 << 0); // Enable clock for TIM2
    TIM2->PSC = 16000 - 1;    // Set prescaler to 16000
    TIM2->ARR = 1000 - 1;     // Set auto-reload register to 1000
    TIM2->CNT = 0;            // Set counter to 0

    set_lcd_mode(CLEAR_SCREEN);
    lcd_print(0, 0, "CLOCK");
    lcd_print(0, 1, hours);
    lcd_print(2, 1, ":");
    lcd_print(3, 1, minutes);
    lcd_print(5, 1, ":");
    lcd_print(6, 1, seconds);
    if (AM)
    {
        lcd_print(9, 1, "AM");
    }
    else
    {
        lcd_print(9, 1, "PM");
    }
}

void timer_delay(uint32_t seconds)
{
    uint32_t counter;
    for (counter = 0; counter < seconds; counter++)
    {
        TIM2->CR1 |= (1 << 0); // Enable timer
        while (!(TIM2->SR & (1 << 0)))
            ;                   // Wait until UIF flag is set
        TIM2->SR &= ~(1 << 0);  // Clear UIF flag
        TIM2->CR1 &= ~(1 << 0); // Disable timer
    }
}

void seconds_increment()
{

    seconds[1]++;
    if (seconds[1] >= '9' + 1)
    {
        seconds[1] = '0';
        seconds[0]++;
        if (seconds[0] >= '5' + 1)
        {
            seconds[0] = '0';
            minutes_increment();
        }
    }

    lcd_print(6, 1, seconds);
}

void minutes_increment()
{
    minutes[1]++;
    if (minutes[1] >= '9' + 1)
    {
        minutes[1] = '0';
        minutes[0]++;
        if (minutes[0] >= '5' + 1)
        {
            minutes[0] = '0';
            hours_increment();
        }
    }

    lcd_print(3, 1, minutes);
}

void hours_increment()
{
    hours[1]++;
    if ((hours[1] >= '2' + 1) && (hours[0] >= '1'))
    {
        hours[1] = '1';
        hours[0] = '0';
        if (AM)
        {
            lcd_print(9, 1, "PM");
            AM = 0;
        }
        else
        {
            lcd_print(9, 1, "AM");
            AM = 1;
        }
    }
    if (hours[1] >= '9' + 1)
    {
        hours[1] = '0';
        hours[0]++;
    }

    lcd_print(0, 1, hours);
}
