/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f405xx.h>

uint32_t volatile *ptr_NVIC_IRQ_EN = (uint32_t *)0xE000E100;

int main(void)
{
    RCC->AHB1ENR |= (1 << 1); // Enable clock for GPIOB
    GPIOB->MODER &= ~(3 << 26);
    GPIOB->MODER |= (1 << 26); // Set PB13 as output

    RCC->APB1ENR |= (1 << 0); // Enable clock for TIM2
    TIM2->PSC = 16000 - 1;    // Set prescaler to 16000
    TIM2->ARR = 1000 - 1;     // Set auto-reload register to 1000
    TIM2->CNT = 0;            // Set counter to 0
    TIM2->CR1 |= (1 << 0);    // Enable TIM2
    TIM2->DIER |= (1 << 0);   // Enable interrupt for TIM2

    // NVIC_EnableIRQ(TIM2_IRQn); // Enable interrupt for TIM2
    *ptr_NVIC_IRQ_EN |= (1 << 28); // Enable interrupt for TIM2

    while (1)
    {
    }
}

void TIM2_IRQHandler()
{
    TIM2->SR &= ~(1 << 0); // Clear interrupt flag

    GPIOB->ODR ^= (1 << 13); // Toggle PB13
}