/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Display Text in LCD
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <lcd.h>

int main(void)
{
    enum lcd_modes a;
    char i[2] = "1";
    lcd_init(BIT_4_MODE);
    lcd_print(0, 0, "Initializing!");
    lcd_print(0, 1, "Please Wait...");

    delay(500);

    set_lcd_mode(CLEAR_SCREEN);
    for (a = 0; a < 12; a++)
    {
        lcd_print(0, 0, "Mode ");
        lcd_print(0, 1, i);
        set_lcd_mode(a);
        i[0]++;
        delay(500);
        set_lcd_mode(CLEAR_SCREEN);
    }

    return 0;
}
