/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Analog to digital conversion using built-in potentiometer
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <common.h>

uint32_t result = 0;

void init();
void check_pot();

int main(void)
{
	init();

	while (1)
	{
		check_pot();
	}
}

void init()
{
	lcd_init(BIT_4_MODE);
	lcd_print(0, 0, "ADC using POT");
	lcd_print(0, 1, "Value:");
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN; // Enable GPIOC clock
	set_analog(GPIOC, 2);				 // Set PC2 as analog (POT1)

	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN; // Enable ADC1 clock
	ADC1->CR2 = 0;						// Disable ADC1
	ADC1->SQR3 |= (0xC << 0);			// Set channel 12 (PC2) as first conversion in regular sequence
	ADC1->SQR1 = 0;						// Set length of regular sequence to 1 conversion
	ADC1->CR2 = 1;						// Enable ADC1
}

void check_pot()
{
	lcd_print_int(7, 1, result, 1); // Print ADC value
	ADC1->CR2 |= 1 << 30;			// Start conversion
	while (!(ADC1->SR & 1 << 1))
		;				   // Wait for conversion to complete
	result = ADC1->DR;	   // Read conversion result
	ADC1->SR &= ~(1 << 1); // Clear EOC flag
}