/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Analog to digital conversion using built-in potentiometer
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <common.h>

uint32_t result = 0;

void init();
void check_pot();

int main(void)
{
	init();

	while (1)
	{
		check_pot();
	}
}

void init()
{
	lcd_init(BIT_4_MODE);
	lcd_print(0, 0, "POT Value:");
	lcd_print(0, 1, "LED");
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN; // Enable GPIOC clock
	set_analog(GPIOC, 2);				 // Set PC2 as analog (POT1)
	set_output(GPIOC, 6);				 // Set PC6 as output (LED1)

	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN; // Enable ADC1 clock
	ADC1->CR2 = 0;						// Disable ADC1
	ADC1->SQR3 |= (0xC << 0);			// Set channel 12 (PC2) as first conversion in regular sequence
	ADC1->SQR1 = 0;						// Set length of regular sequence to 1 conversion
	ADC1->CR2 = 1;						// Enable ADC1
}

void check_pot()
{
	lcd_print_int(11, 0, result, 1); // Print ADC value
	ADC1->CR2 |= 1 << 30;			 // Start conversion
	while (!(ADC1->SR & 1 << 1))
		;			   // Wait for conversion to complete
	result = ADC1->DR; // Read conversion result
	if (result < 2048) // If POT1 value is greater than 2048
	{
		set_bit(GPIOC, 6);		// Turn OFF LED1
		lcd_print(4, 1, "OFF"); // Print "OFF" on LCD
	}
	else
	{
		clr_bit(GPIOC, 6);		// Turn On LED1
		lcd_print(4, 1, "ON "); // Print "ON" on LCD
	}
	ADC1->SR &= ~(1 << 1); // Clear EOC flag
}
