/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Timer delay
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f405xx.h>

void delay(uint32_t);

int main(void)
{
    RCC->AHB1ENR |= (1 << 2); // Enable clock for GPIO Port C
    GPIOC->MODER |= (1 << 12);
    GPIOC->MODER &= ~(1 << 13); // Set PC6 to output mode (LED1)

    RCC->APB1ENR |= (1 << 0); // Enable clock for TIM2
    TIM2->PSC = 16000 - 1;    // Set prescaler to 16000
    TIM2->ARR = 1000 - 1;     // Set auto-reload register to 1000
    TIM2->CNT = 0;

    while (1)
    {
        GPIOC->ODR &= ~(1 << 6); // Turn on LED
        delay(1);
        GPIOC->ODR |= (1 << 6); // Turn off LED
        delay(1);
    }
}

void delay(uint32_t seconds)
{
    uint32_t counter;
    for (counter = 0; counter < seconds; counter++)
    {
        TIM2->CR1 |= (1 << 0); // Enable timer
        while (!(TIM2->SR & (1 << 0)))
            ;                   // Wait until UIF flag is set
        TIM2->SR &= ~(1 << 0);  // Clear UIF flag
        TIM2->CR1 &= ~(1 << 0); // Disable timer
    }
}
