/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Use PWM Timer to control LED intensity
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <common.h>

void init_led(void);
void init_timer(void);
void init_pwm(void);

int main(void)
{
    init_led();
    init_timer();
    init_pwm();

    while (1)
    {
    }
}

void init_led(void)
{
    RCC->AHB1ENR |= (1 << 2); // Enable GPIOC clock
    set_alternate(GPIOC, 6);  // Set PC6 to alternate function
}

void init_timer(void)
{
    RCC->APB1ENR |= (1 << 0); // Enable TIM2 clock
    TIM2->PSC = 0;            // Prescaler value
    TIM2->ARR = 1000;         // Auto-reload value
    TIM2->CR1 |= (1 << 0);    // Enable TIM2
}

void init_pwm(void)
{
    TIM2->CCMR1 |= (1 << 3); // Set output compare 1 mode to PWM mode 1
    TIM2->CCMR1 |= (1 << 6); // Set output compare 2 mode to PWM mode 1
    TIM2->CCMR2 |= (1 << 3); // Set output compare 3 mode to PWM mode 1
    TIM2->CCMR2 |= (1 << 6); // Set output compare 4 mode to PWM mode 1

    TIM2->CCER |= (1 << 0);  // Enable output compare 1
    TIM2->CCER |= (1 << 4);  // Enable output compare 2
    TIM2->CCER |= (1 << 8);  // Enable output compare 3
    TIM2->CCER |= (1 << 12); // Enable output compare 4

    TIM2->CCR1 = 0; // Set output compare 1 to 0
    TIM2->CCR2 = 0; // Set output compare 2 to 0
    TIM2->CCR3 = 0; // Set output compare 3 to 0
    TIM2->CCR4 = 0; // Set output compare 4 to 0

    TIM2->BDTR |= (1 << 15); // Enable main output
}